export const POSTS_LIST_REQUEST='POSTS_LIST_REQUEST';
export const POSTS_LIST_SUCCESS='POSTS_LIST_SUCCESS';
export const POSTS_LIST_FAIL='POSTS_LIST_FAIL';

export const POST_DETAIL_REQUEST='POST_DETAIL_REQUEST';
export const POST_DETAIL_SUCCESS='POST_DETAIL_SUCCESS';
export const POST_DETAIL_FAIL='POST_DETAIL_FAIL';

export const POSTS_CREATE_REQUEST='POSTS_CREATE_REQUEST';
export const POSTS_CREATE_SUCCESS='POSTS_CREATE_SUCCESS';
export const POSTS_CREATE_FAIL='POSTS_CREATE_FAIL';

export const POSTS_UPDATE_REQUEST='POSTS_UPDATE_REQUEST';
export const POSTS_UPDATE_SUCCESS='POSTS_UPDATE_SUCCESS';
export const POSTS_UPDATE_FAIL='POSTS_UPDATE_FAIL';

export const POSTS_DELETE_REQUEST='POSTS_DELETE_REQUEST';
export const POSTS_DELETE_SUCCESS='POSTS_DELETE_SUCCESS';
export const POSTS_DELETE_FAIL='POSTS_DELETE_FAIL';

export const POSTS_LIKE_REQUEST ='POSTS_LIKE_REQUEST';
export const POSTS_LIKE_SUCCESS ='POSTS_LIKE_SUCCESS';
export const POSTS_LIKE_FAIL ='POSTS_LIKE_FAIL';


export const COMMENT_REQUEST ='COMMENT_REQUEST';
export const COMMENT_SUCCESS ='COMMENT_SUCCESS';
export const COMMENT_FAIL ='COMMENT_FAIL';